### PR TITLE
feat: support nested menus

### LINKED ISSUE #47: Nested Menu Alignment
If you have more than one level of menu entries the layout for some reason does not look right. I am not sure if this is known or by design. Here is the code: 

```
- ## Catalog
    - [Structure](/docs/{{version}}/catalog/structure)
    - [Documents](/docs/{{version}}/catalog/documents)
        - [Product](/docs/{{version}}/catalog/documents/product)
        - [Category](/docs/{{version}}/catalog/documents/catrgory)
```
And the Screenshot:

nested-menu

### PR DESCRIPTION
**Pull request by kalynrobinson**
Resolves #47.

### CODE REVIEW

**Comment by saleem-hadad** [comment]
Thank you @kalynrobinson 🌸

**Comment by shamsuljewel** [comment]
Hi, how to hide the menus that the user does not have any permission to see? Or only show the nested menus which is selected now.

**Comment by WillGoldstein** [comment]
@shamsuljewel  read the docs https://larecipe.binarytorch.com.my/docs/2.2/authorization

**Comment by shamsuljewel** [comment]
@WillGoldstein I have already implemented the Gate authorization in my project, it works well as with this shows a 403 page when user access a documentation url that user does not has the permission. But how can I hide the sidebar menu to hide those left menu to hide that the user does not has the permission, I added the sidebar.blade.php partials for the sidebar. But how can do like $user->hasPermission(route) show the menu ?

**Comment by WillGoldstein** [comment]
I don't think that functionality exists right now

**Comment by shamsuljewel** [comment]
Well What I am doing right now, using the @can derictive
`@can('viewLarecipe', 'internal/setup')
        <li><a href="/docs/{{ $currentVersion }}/internal/setup">Setup</a></li>
 @endcan`

And in the gate checking if the current user has the permission for that route, at least its working for the moment.

**Pull request merged**
