### PR TITLE
parsedown-extra support for php7.4

### PR DESCRIPTION
**Pull request by drjdr**

### CODE REVIEW

**Comment by ayimdomnic** [comment]
@saleem-hadad Can this be merged?

**Comment by derweba** [comment]
@saleem-hadad yea, i would also really apreciate if you merge this.

**Comment by hedeqiang** [comment]
Can this be merged?

**Comment by SerafimArts** [comment]
@drjdr can you please publish your fork on the packagist? Since, apparently, corrections in main repo in the near future we will not wait.)))

**Comment by TheFrankman** [comment]
@saleem-hadad - bump

**Comment by ayimdomnic** [comment]
@SerafimArts I agree with you.. looks like this is no-longer maintained

**Comment by WillGoldstein** [comment]
It's still maintained. @saleem-hadad has started up a discord with some of the contributors (myself included) with the goal of making it better. Unfortunately, he hasn't given anyone any power yet, and has been unresponsive lately.

**Comment by drjdr** [comment]
@SerafimArts Let's first find out why there is no response anymore before starting a fork on which projects will depend. 
I use the following currently for a small project on mine where I use this for the docs.

`        "binarytorch/larecipe": "dev-master",
`
Change the required version to dev-master

```
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/drjdr/larecipe"
        }
    ]

```
Add the above to your composer.json file, which will help you until this gets merged.
See https://getcomposer.org/doc/05-repositories.md#vcs

I have seen that the tests are very limited in this projects, e.g. the last commit solves an issue which you get when generating the docs. But all the tests succeeded already the commit before :/

**Comment by SerafimArts** [comment]
@drjdr I can’t do this, since the assembly servers do not have access to the github (security reasons), and all the inquiries go to the [artifactory](https://jfrog.com/artifactory/), which in turn goes to the packagist.

**Comment by drjdr** [comment]
> @drjdr I can’t do this, since the assembly servers do not have access to the github (security reasons), and all the inquiries go to the [artifactory](https://jfrog.com/artifactory/), which in turn goes to the packagist.
@SerafimArts Feel free to fork my patch and add it to your packagist as well. It will keep you in control of your code and requirements. I have no intent of maintaining a version of this software. :)

**Comment by SerafimArts** [comment]
@drjdr kk, thx

**Comment by SerafimArts** [comment]
If someone needs it: https://packagist.org/packages/serafim/larecipe v2.3.0

**Comment by saleem-hadad** [comment]
Sorry guys for being late, I was on holiday with my family recently

**Comment by saleem-hadad** [comment]
I'll release a new version tonight

**Comment by saleem-hadad** [comment]
thank you all, this project is still maintained periodically
don't worry

**Comment by drjdr** [comment]
Congrats Saleem! and thanks for merging

**Pull request merged**
