### PR TITLE
Laravel 10 Support

### PR DESCRIPTION
**Pull request by RohanSakhale**

### CODE REVIEW

**Comment by RohanSakhale** [comment]
@saleem-hadad can you please check this and approve to support Laravel 10 upgrade

**Comment by saleem-hadad** [comment]
thanks, sure I'll test soon

**Comment by OzanKurt** [comment]
@saleem-hadad

Hello there,

can you please give us an ETA?

**Comment by RohanSakhale** [comment]
@saleem-hadad I tried running tests locally and below is the result

image

**Comment by saleem-hadad** [comment]
the update is available in v2.6.0. Thanks guys

**Pull request merged**
