### PR TITLE
Change Prism to Autoload languages

### PR DESCRIPTION
**Pull request by tankerkiller125**
## Description
This pull request will allow Prism to automatically load all supported Prism languages from the official Prism CDN, this increases the currently supported list of languages from the very small amount to literally everything that prism can do.

This pull request also removes all languages except for the ones marked as "Core" on the Prism download site.

## Test
N/A

## Documentation Changes
I will make a pull request on the larecipe-docs repo after this request gets merged

## Breaking Changes?
None, current functionality remains the same but is expanded to more languages.

### CODE REVIEW

**Comment by saleem-hadad** [comment]
Awesome 🔥
Thank you @tankerkiller125 for your contribution. You guys are amazing 😍

**Comment by tankerkiller125** [comment]
You should be able to use the markdown just like always, the prism autoload plugin will automatically go to prism CDN and retrieve the correct files.

**Comment by tankerkiller125** [comment]
@OwenMelbz which browser are you using? And if you open the developers tools under network do you see the PRISM CDN request?

**Comment by OwenMelbz** [comment]
@tankerkiller125 yeah it was downloading it correctly, I think the problem was that the CSS required for the styling wasn’t hooking in.

I downloaded the css file on the lararecipe website and replaced and it fixed it.

So was almost like the source code version which was published didn’t support it maybe

**Comment by tankerkiller125** [comment]
The source code version should be work properly, I published the CSS and JS change, so I'm really not sure what happened in your case

**Pull request merged**
