### PR TITLE
Laravel 7 Support

### PR DESCRIPTION
**Pull request by matthewnessworthy**

### CODE REVIEW

**Comment by WillGoldstein** [comment]
Geeze already at 7. Thanks for doing this. Did it pass the unit tests as well?

**Comment by matthewnessworthy** [comment]
@WillGoldstein Tests are now passing (and the warnings are gone too)

**Comment by WillGoldstein** [comment]
Awesome job thanks @matthewnessworthy - I would merge but I don’t have the ability.

**Comment by matthewnessworthy** [comment]
@WillGoldstein I'm sure @saleem-hadad will merge it when he has a spare moment

**Comment by saleem-hadad** [comment]
Thank you guys 🌹🤓

**Comment by matthewnessworthy** [comment]
@saleem-hadad would you mind publishing a new release with this change? 2.2.3 was published on the 21st of Jan

**Comment by saleem-hadad** [comment]
Hello guys, 
A new release just published with tag [v2.3.0](https://github.com/saleem-hadad/larecipe/releases/tag/v2.3.0)

**Pull request merged**
