### PR TITLE
Allow Laravel 6.0

### PR DESCRIPTION
**Pull request by matthewnessworthy**

### CODE REVIEW

**Comment by stygiansabyss** [comment]
Any chance this could be added?  ping @saleem-hadad

**Comment by harlekoy** [comment]
Tried this but we have a bug in the code as well

```
☁  website [laravel-6-upgrade] ⚡ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing symfony/dom-crawler (v4.3.4): Loading from cache
  - Installing erusev/parsedown-extra (0.7.1): Loading from cache
  - Installing binarytorch/larecipe (dev-master a7a1d74): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   ErrorException  : Declaration of BinaryTorch\LaRecipe\Commands\AssetCommand::runCommand($command, $path) should be compatible with Illuminate\Console\Command::runCommand($command, array $arguments, Symfony\Component\Console\Output\OutputInterface $output)

  at /Users/harlequindoyon/Sites/prophet/website/vendor/binarytorch/larecipe/src/Commands/AssetCommand.php:305
    301|         foreach ($this->stubsToRename() as $stub) {
    302|             (new Filesystem)->move($stub, str_replace('.stub', '.php', $stub));
    303|         }
    304|     }
  > 305| }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Declaration of BinaryTorch\LaRecipe\Commands\AssetCommand::runCommand($command, $path) should be compatible with Illuminate\Console\Command::runCommand($command, array $arguments, Symfony\Component\Console\Output\OutputInterface $output)", "/Users/harlequindoyon/Sites/prophet/website/vendor/binarytorch/larecipe/src/Commands/AssetCommand.php", ["/Users/harlequindoyon/Sites/prophet/website/vendor/composer/../binarytorch/larecipe/src/Commands/AssetCommand.php"])
      /Users/harlequindoyon/Sites/prophet/website/vendor/composer/ClassLoader.php:444

  2   include()
      /Users/harlequindoyon/Sites/prophet/website/vendor/composer/ClassLoader.php:444

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
☁  website [laravel-6-upgrade] ⚡
```

**Comment by harlekoy** [comment]
@matthewnessworthy maybe you can send to us the result of the test cases

**Comment by matthewnessworthy** [comment]
I've updated the PR to allow Laravel 5 & 6, and the dev dependencies to be Laravel 6 only. TBH, I'm not sure what the best way of supporting both Laravel 5 & 6 is without having separate branches.

**Comment by matthewnessworthy** [comment]
@saleem-hadad Would you mind taking a look at this PR and either approving it, or recommending changed.

Without an update like this I (and I'm sure many others) cannot upgrade to Laravel 6.x

**Comment by asivaneswaran** [comment]
@saleem-hadad Was wondering the same thing. I rather not fork this package just for this PR...

**Comment by djekl** [comment]
Has anyone tested this? I tried using the fork used for this PR and got the same issue as @harlekoy

**Comment by saleem-hadad** [comment]
Hello guys
Sorry for being late I was busy with my work. I'll look at this tonight hopefully :)

**Comment by matthewnessworthy** [comment]
I see that Laravel 6 added the method `runCommand` that just so happens to conflict with the LaRecipe `runCommand`

I've moved the code in question into a trait (as it's shared between 2 commands), and renamed it to avoid conflicting with the new Laravel function. 

@harlekoy sorry for the trouble, but would you mind retesting with the updated code?

**Comment by harlekoy** [comment]
Hi @matthewnessworthy yes i'll try to test later :)

**Comment by harlekoy** [comment]
image
@matthewnessworthy working fine in my end 😄

**Comment by harlekoy** [comment]
But the problem is that after i installed and rerun this command `php artisan larecipe:install` it says 
too many redirects

image
@matthewnessworthy is it working in your end?

**Comment by saleem-hadad** [comment]
I'll merge this and fix any issues on my end if found

**Comment by WBDC** [comment]
Hi guys, 

I tried to upgrade to L6, but seems like its still a no go. 
Currently I use L58 and php 7.2.14

image

**Pull request merged**
