### PR TITLE
Disable interpolation

### LINKED ISSUE #28: Blade syntax break resolution
**Describe the bug**
When using a snippet that contains blade, the documentation page will no longer load in a browser

**To Reproduce**
```blade
    <a href="{{ route('auth.social.login', ['google']) }}">Log in with Google</a>
    <a href="{{ route('auth.social.login', ['github']) }}">Log in with Github</a>
```

Place this snippet anywhere in a larecipe markdown file.

**Expected behavior**
It should show blade syntax as just text.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Additional Information**
I even tried using `&#123;` and `&#125;` for the braces but it just displays them as is instead of converting to curly brackets.

### PR DESCRIPTION
**Pull request by phannaly**
Disable interpolation to allow `{{` `}}` syntax in markdown.
This PR will fix #28

### CODE REVIEW

**Comment by saleem-hadad** [comment]
Thank you @phannaly for your contributions 👻. However, I tried this PR, but it seems doesn't solve the problem completely I mean the blade syntax still not rendering! 🧐

**Comment by phannaly** [comment]
@saleem-hadad Have you try rebuilt the assets?

**Comment by phannaly** [comment]
Seems work perfectly for me. if you still have problem, I will check my PR again.
https://i.imgur.com/2uy8j4S.png

**Comment by saleem-hadad** [comment]
Yes correct that what I got also, but this doesn't seem to solve the issue completely (only half of it), because what they are trying to do is to render the blade syntax now showing it as text

**Comment by phannaly** [comment]
ah! sorry I missed the point. I will check it tonight.

**Comment by saleem-hadad** [comment]
Thank you dude for your help and contribution :D

**Comment by phannaly** [comment]
@saleem-hadad can you check these commit again?
I just add commit to render blade syntax then parse to markdown.
As Blade function need `Illuminate/view` I also update composer.json in require.

**Comment by phannaly** [comment]
@saleem-hadad That's okay I just realized I missed unit test.

**Comment by phannaly** [comment]
Just add unit test for check and render blade syntax.

**Comment by saleem-hadad** [comment]
Amazing ❤️😍
Thank you very much @phannaly for your awesome contributions 🎊

**Comment by OwenMelbz** [comment]
@saleem-hadad @phannaly are you sure this has been resolved?

When using 1.2.5 and this markdown..

blade_md_ _giles-docs

I get the blade error

whoops__there_was_an_error_

However when I then I use the blade escape e.g `@`

blade_md_ _giles-docs

Yes blade ignores it - however Vue still tries to parse it.

_blade_-_giles

The HTML that it outputs is

```html
<pre><code class="language-php">Hello {{ $example }}</code></pre>
```

**Comment by phannaly** [comment]
Hi @OwenMelbz Did you already pass $example variable to your markdown file?

**Comment by OwenMelbz** [comment]
No because it's documentation giving examples :D

I want the documentation to show users how to do things, and this instance the documentation is explaining how to do something that uses blade syntax with an example variable

**Comment by phannaly** [comment]
@OwenMelbz You have to pass your $variable from `DocumentationController` inside `show()` method so markdown file will clearly know what it is. 
@saleem-hadad Can you make docs for this or need some PR?

**Comment by OwenMelbz** [comment]
@phannaly This doesn't make sense.

This package is for Writing documentation.

It becomes useless if you try parse the code, meaning people cannot write code examples.

--

For example, lets just say you were trying to inform your users how to pass data from a controller to your view, you might write something like... (using laravel as an example).

**Please imagine below is the documentation I want to write:**

# EXAMPLE START

First you need to set up your route e.g.

```php
Route::get('/', 'HomeController');
```

Once you've defined your route, you can make your controller e.g.

```php
<?php

namespace App\Http\Controllers;

class HomeController
{
    public function __invoke()
    {
        return view('home')->with('message', 'Hello World');
    }
}

```

Now within your blade template e.g. `home.blade.php` you can display your `$message` variable e.g.

```html
@extends('layout.app')

@section('content')
    <h1>{{ $message }}</h1>
@endsection
```

# EXAMPLE END

---

You can see here that I'm simply describing how to display a variable in blade.

What you're saying is that I need to pass a variable from the controller to the docs... this doesn't make sense.

Hopefully you understand why this is wrong.

Thanks

**Comment by phannaly** [comment]
@OwenMelbz That's why I ask creator to create docs.

**Comment by OwenMelbz** [comment]
@phannaly but how can we now do the above?

It was working before the PR was merged I believe

**Comment by OwenMelbz** [comment]
@saleem-hadad what’s going on with this please? We’ve just spent ages writing our docs in your tool, loving the product, now it’s currently unusable and really hoping you can find a solution :(

**Comment by saleem-hadad** [comment]
sorry guys I didn't get notification about what's going on here

**Comment by saleem-hadad** [comment]
I'll check now

**Comment by OwenMelbz** [comment]
@saleem-hadad Maybe something else is needed to get this working on existing projects?

e.g. This is our composer installed versoin

```
➜ composer show | grep "lare"
binarytorch/larecipe                  v1.2.5   Generate gorgeous recipes ...
```

This is a markdown file

    # 🔪 Blade

    ---

    ```php
    hello {{ $test }}
    ```

This is the error

screen shot 2018-10-07 at 16 34 44

--

@saleem-hadad Perhaps I could share the code-base with you privately to see if you can replicate?

**Comment by saleem-hadad** [comment]
@OwenMelbz no problem I'd be happy to help 😇
but as I told you just add "@" before any variable you have. e.g. "@{{ $test }}" instead of "{{ $test }}"

and make sure you publish the new assets
```
php artisan vendor:publish --tag=larecipe_assets --force
```

If noting works, add me to the repo temporarly to try fixing the issue.

**Comment by OwenMelbz** [comment]
Publishing the new assets seemed to be the fix here!

After that it worked as expected :P

Was that listed somewhere that I missed, or does it need adding?

Thanks :)

**Comment by saleem-hadad** [comment]
Cool, sounds great 😍

Yead dude, it's mentioned in the [upgrade section](https://larecipe.binarytorch.com.my/docs/1.2/upgrade)
but nevermind :D 
Good luck with your project/package @OwenMelbz 😍please share it with us if you can once you publish it, we'll be happy to see it live

**Pull request merged**
