### PR TITLE
[Enhancement] a bit dirty allowing different guard per published version

### PR DESCRIPTION
**Pull request by alberto1el**
With passing tests.

This allows to have different guard per published version. 
Could be something like:

```
 'versions'=> [
        'default'   => 'user-1.0',
        'published' => [
            [
                'version' => 'user-1.0',
                'auth'  => true,
                'guard'  => 'web',
                'auth_links' => [
                    [
                        'name' => '',
                        'url' => '',
                    ],
                ],
            ],
            [
                'version' => 'admin-1.0',
                'auth'  => true,
                'guard'  => 'admin',
                'auth_links' => [
                    [
                        'name' => '',
                        'url' => '',
                    ],
                ],
            ]
        ]
    ],
```

### CODE REVIEW

**Comment by phannaly** [comment]
@saleem-hadad A bit quite from you.

**Comment by saleem-hadad** [comment]
Hi @alberto1el thanks for your contribution. However, I've another idea to be implemented without changing the config file.
If you look here in the DocumentationController [show](https://github.com/saleem-hadad/larecipe/blob/master/src/Http/Controllers/DocumentationController.php#L50) method

```php
if (Gate::has('viewLarecipe')) {
    $this->authorize('viewLarecipe', $documentation);
}
```

We can add another param to the `authorize` method which is the `$version` so that the end user can  do whatever logic he prefere:

```php
if (Gate::has('viewLarecipe')) {
    $this->authorize('viewLarecipe', $documentation, $version);
}
```

What do you think?

**Comment by saleem-hadad** [comment]
@phannaly  thanks dude I was busy a bit with my study now I come back to life 💃

**Comment by alberto1el** [comment]
Oh I see it now, it is a good way to do it, awesome!

**Pull request closed without merging**
