### PR TITLE
Make sidebar link display as block.

### PR DESCRIPTION
**Pull request by overtrue**

### CODE REVIEW

**Comment by saleem-hadad** [comment]
Thank you @overtrue for contributions, but can you provide a screenshot of the diff. you made with this PR?

**Comment by overtrue** [comment]
Yes, This changes just make a wide clickable area:

before:

image

after:
image

The red area is clickable.

**Comment by overtrue** [comment]
qq20181006-133925-hd

qq20181006-133832-hd

**Comment by saleem-hadad** [comment]
Cool, Thanks 👻

**Comment by overtrue** [comment]
@saleem-hadad 😆

**Pull request merged**
